### ISSUE TITLE
Problem with plasmid_contigs.fasta

### ISSUE THREAD

**Issue by varunshamanna** [lisavader/plasmidEC#10]
The contigs are not complete

![image](https://user-images.githubusercontent.com/43167012/170979476-90b37b65-e77f-44b3-a694-831e7a200cbe.png)

I added seqtk to get the fasta and I wanted the file name in the contigs. So add these things in the write_plasmid_contigs.sh
```
for contig in $plasmid_contigs; do
        echo $contig >> $out_dir/contig.txt
        #grep -A 1 $contig $input >> $out_dir/plasmid_contigs.fasta
done

TAG="$(basename $input .fasta)"
seqtk subseq $input $out_dir/contig.txt >> $out_dir/"${TAG}"_plasmids.fasta
sed -i "s/^>/>${TAG}_/" $out_dir/"${TAG}"_plasmids.fasta
```

Because the -A 1 in grep does grep only subsequent line after the header.
```
-A, --after-context=NUM   print NUM lines of trailing context
```
The contigs from spades are never in a single line.

**Comment by lisavader** [comment]
Hi Varun,
I had indeed not realised that this script doesn't work for contigs spanning multiple lines, thanks for notifying!
It has been adjusted now (584750d9625a7f78457c301744e1d22982041daa)

**Comment by varunshamanna** [comment]
Thank you for the updates.
I just wanted to check what are your thoughts on running the tool for multiple samples? And combining the results together?

**Comment by lisavader** [comment]
Actually, in a previous version of the tool a directory was used as input, and plasmidEC would output the combined result for all files in this directory. However, I changed this to a one file in --> one file out approach, so that the tool can be more easily integrated in pipelines (e.g. Snakemake) and users can run multiple jobs in parallel, using whatever job scheduler they like. So more possibilities for costumisation, with the cost that you'll have concatenate the results of multiple samples yourself.
